server:
  port: 80
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${QING_MYSQL_HOST}:${QING_MYSQL_PORT}/qing?serverTimezone=UTC
    hikari:
      username: ${QING_MYSQL_USERNAME}
      password: ${QING_MYSQL_PASSWORD}
  mail:
    host: ${QING_MAIL_HOST}
    username: ${QING_MAIL_USERNAME}
    password: ${QING_MAIL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%5p] --- [%-24t] [%-50C{50}][%-6L]: %m%n"
  level:
    root: info
    person.pluto: info
    cn.chenyunlong.qing: info
    cn.chenyunlong.qing.mapper: info
mp:
  wx:
    app-id: ${QING_WECHAT_APPID}
    secret: ${QING_WECHAT_SECRET}
qing:
  file:
    baseUploadDir: upload/
    image-server-url: https://bangumi.chenyunlong.cn
    # 是否异步记录用户操作日志
  openAopLog: true
  swagger:
    doc-disabled: true
