server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-e1mnik7m.sql.tencentcdb.com:28661/qing?serverTimezone=UTC
    hikari:
      username: root
      password: MysqlPwdROOT1996
  mail:
    host: smtp.qq.com
    username: 1576302867@qq.com
    password: uqvyyxhvhdpnbabg
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli
    fetch-registry: true
    register-with-eureka: true
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%5p] --- [%-24t] [%-50C{50}][%-6L]: %m%n"
  level:
    root: info
    person.pluto: info
    cn.chenyunlong.qing: info
    cn.chenyunlong.qing.mapper: info
mp:
  wx:
    appId: wx09bf7e704a150a9c
    secret: 9fdb9fa846356d32247a9aa68d758791
zhangli:
  file:
    baseUploadDir: upload/
    image-server-url: https://bangumi.chenyunlong.cn
  # 是否异步记录用户操作日志
  openAopLog: true
  swagger:
    doc-disabled: true
