server:
  port: 80
spring:
  profiles:
    active: local
  application:
    name: qing-service-anime
  messages:
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    hikari:
      connection-timeout: 6000
      validation-timeout: 1000
      idle-timeout: 60000
      login-timeout: 500
      max-lifetime: 60000
      maximum-pool-size: 2
      minimum-idle: 1
      read-only: false
      connection-test-query: SELECT 1
      initialization-fail-timeout: 1000
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 10MB
  freemarker:
    template-loader-path: classpath:/templates/mail/
    suffix: .ftl
  cache:
    type: simple
  quartz:
    scheduler-name: testName
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: true
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        dialect: org.hibernate.dialect.MariaDBDialect
mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    banner: false
  type-aliases-package: cn.chenyunlong.qing.**.domain,cn.chenyunlong.qing.**.entities
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 是否异步记录用户操作日志
  openAopLog: true
  swagger:
    author: Stan
    basePackage: cn.chenyunlong.qing
    description: My Rear Garden API Documentation.
    email: 1576302867@qq.com
    license: MulanPSL-2.0
    licenseUrl: http://license.coscl.org.cn/MulanPSL2
    title: Application from Project Qing
    url: https://bangumi.chenyunlong.cn
    version: V1.0.0
    doc-disabled: false
  security:
    secret-key: authentication_
  index-size: 26
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    doc-expansion: none
    default-model-expand-depth: 20
  show-actuator: true
eureka:
  client:
    service-url:
      defaultUrl: ${QING_EUREKA_ADDR:http://localhost:8761}/eureka
liteflow:
  rule-source: flow/flow.el.xml
