server:
  port: 8080
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/qing?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 123456
  thymeleaf:
    cache: false
    prefix: file:${user.dir}/qing-service-anime/src/main/resources/templates/
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
  mail:
    host: smtp.qq.com
    username: 1576302867@qq.com
    password: xyshwmdggdtqfjhb
  cache:
    type: none
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    hostname: 127.0.0.1
    namespace: qing
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mp:
  wx:
    appId: wx09bf7e704a150a9c
    secret: 9fdb9fa846356d32247a9aa68d758791
qing:
  file:
    baseUploadDir: upload/
    image-server-url: http://localhost:8080
  # 是否异步记录用户操作日志
  openAopLog: true
  swagger:
    doc-disabled: false
  index-size: 26
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

