spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/qing?serverTimezone=GMT%2B8&
    hikari:
      username: root
      password: 123456
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
  mail:
    host: ${QING_MAIL_HOST:smtp.qq.com}
    username: ${QING_MAIL_USERNAME:your_mail_count}
    password: ${QING_MAIL_PASSWORD:your_mail_token}
mp:
  wx:
    appId: ${QING_WECHAT_APPID}
    secret: ${QING_WECHAT_SECRET}
qing:
  file:
    baseUploadDir: upload/
    image-server-url: http://${QING_SERVICE_ANIME_HOST}
  # 是否异步记录用户操作日志
  openAopLog: true
  swagger:
    doc-disabled: false
  index-size: 26
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
