server:
  port: 8989
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    protocol: ${SERVER_SSL_PROTOCOL:TLS}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
    key-store: ${SERVER_SSL_KEY_STORE_PATH:}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:}
spring:
  application:
    name: zhangli-service-natcross-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: root
    url: jdbc:mysql://localhost:3306/zhangli?serverTimezone=UTC
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
    hostname: natcross-provider
    prefer-ip-address: true
    ip-address: 121.36.163.95
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli
mybatis:
  mapperLocations: classpath*:mapper*/*.xml
  configuration:
    default-statement-timeout: 30
natcross:
  ## 交互密钥和签名key
  aes-key: ${NATCROSS_AES_KEY:8AUWlb+IWD+Fhbs0xnXCCg==}
  token-key: ${NATCROSS_TOKEN_KEY:tokenKey}
  cert:
    ## 证书存放的基础路径
    base-path: ${CERT_BASE_PATH:}
    ## 默认证书文件名，采用相对路径的方式，只支持pkcs12格式证书
    default-cert-name: ${DEFAULT_CERT_NAME:}
    ## 默认证书密码
    default-cert-password: ${DEFAULT_CERT_PASSWORD:}
  client:
    listen-port: ${NATCROSS_CLIENT_SERVICE_PORT:10010}