debug: false
eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
logging:
  level:
    chenyunlong: debug
management:
  endpoints:
    web:
      exposure:
        include: ["health","httptrace", "metrics"]

server:
  port: 8080
spring:
  application:
    name: zhangli-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: root
      username: root
    url: jdbc:mysql://localhost:3306/zhangli?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  redis:
    database: 0
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 4MB
zhangli:
  file:
    baseUploadDir: G:/upload/
    image-server-url: http://www.stanic.xyz/pic/
  openAopLog: true # 是否异步记录用户操作日志
  swagger:
    author: Stan
    basePackage: chenyunlong.zhangli
    description: Zhanngli's Rear Gargen  API Document.
    email: 1576302867@qq.com
    license: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
    title: Stan's Application for Zhangli
    url: http://www.chenyunlong.cn
    version: 2.0
