eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
    ip-address: 127.0.0.1
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli
    register-with-eureka: true
    fetch-registry: true