server:
  port: 10086
spring:
  application:
    name: zhangli-admin-server
  profiles:
    active: dev
eureka:
  instance:
    hostname: admin.chenyuunlong.cn
    leaseRenewalIntervalInSeconds: 10
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
    prefer-ip-address: false

  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/