server:
  port: 10086
spring:
  application:
    name: zhangli-admin-server
  profiles:
    active: ${ENV:dev}
  security:
    # 配置登录用户名和密码
    user:
      name: macro
      password: 123456
  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS