apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qing
  name: admin-deploy
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      restartPolicy: Always
      containers:
        - name: admin
          image: stanic-docker.pkg.coding.net/qing/qing/qing-bootstrap-admin:0.0.2.64
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp-10086
              containerPort: 10086
          env:
            - name: QING_CONSUL_HOST
              value: {{ .Values.consul.host}}
            - name: QING_CONSUL_PORT
              value: {{ .Values.consul.port}}
            - name: TZ
              value: Asia/Shanghai
            - name: LANG
              value: zh_CN.UTF-8

---
kind: Service
apiVersion: v1
metadata:
  namespace: qing
  name: admin-app
  labels:
    app: admin
spec:
  selector:
    app: admin
  type: NodePort
  ports:
    - name: tcp-31086
      port: 10086
      protocol: TCP
      targetPort: 10086
      nodePort: 31086
