kind: Service
apiVersion: v1
metadata:
  namespace: qing
  name: admin-app
  labels:
    app: admin
spec:
  selector:
    app: admin
  type: NodePort
  ports:
    - name: tcp-31086
      port: 10086
      protocol: TCP
      targetPort: 10086
      nodePort: 31086
