server:
  port: 9001
spring:
  application:
    name: zhangli-feign-client
  profiles:
    active: dev
ribbon:
  eureka:
    enabled: true
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
  client:
    fetch-registry: true
    register-with-eureka: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  endpoint:
    health:
      show-details: always

test: default