server:
  port: 9001
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka