server:
  port: 9528
spring:
  application:
    name: spring-cloud-api-gateway
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://localhost:8001
          filters:
            - StripPrefix=1
          predicates:
            - After=2019-09-24T16:30:00+08:00[Asia/Shanghai]
            - Path=/api/**
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: cloud-gateway
    prefer-ip-address: true
    ip-address: 121.36.163.95
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli