debug: true
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/