server:
  port: 9528
spring:
  application:
    name: spring-cloud-api-gateway
  cloud:
    gateway:
      routes:
        - id: zhangli-service-provider
          uri: lb://zhangli-service-provider
          filters:
            - StripPrefix=1
          predicates:
            - After=2019-09-24T16:30:00+08:00[Asia/Shanghai]
            - Path=/anime/**
        - id: zhangli-service-natcross-provider
          uri: lb://zhangli-service-natcross-provider
          filters:
            - StripPrefix=1
          predicates:
            - Path=/natcross/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/mall-auth/rsa/publicKey' #配置RSA的公钥访问地址
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: cloud-gateway
    prefer-ip-address: true
    ip-address: 121.36.163.95
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always