server:
  port: 7894
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: MysqlPwdROOT1996
    url: jdbc:mysql://cdb-4fyv2fr8.cd.tencentcdb.com:10085/zhangli?serverTimezone=UTC
echoserver:
  port: 5959