server:
  port: 8888
spring:
  application:
    name: qing-config-git
  profiles:
    active: prod
  cloud:
    config:
      server:
        default-label: master
        git:
          search-paths: config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: default
      status: UP
      profile: prod
