server:
  port: 8888
spring:
  application:
    name: qing-config-git
  profiles:
    active: prod
  cloud:
    consul:
      host: ${CONSUL_HOST:1.15.242.253}
      port: ${CONSUL_PORT:8500}
      discovery:
        register-health-check: true
        prefer-ip-address: true
        ip-address: ${CONFIG_IP:127.0.0.1}
    config:
      server:
        default-label: master
        git:
          search-paths: config-repo
