eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli
    service-url:
      defaultZone: https://eureka.chenyunlong.cn/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/stanChen/zhangli-config.git
          username: stanChen
          password: 4745701816long