server:
  port: 8888
spring:
  application:
    name: qing-config-git
  profiles:
    active: prod
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}
    metadata-map:
      startup: ${random.int}
  client:
    registryFetchIntervalSeconds: 30
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
