version: '2'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - zhangli
    ports:
      - "6379:6379"
    env_file: .env
  service-provider:
    networks:
      - zhangli
    container_name: service-provider
    image: stanic-docker.pkg.coding.net/zhangli/zhangli/zhangli-service-provider:1.0.0.RELEASE
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
      NACOS_SERVER: nacos:8848
    links:
      - redis:redis
    env_file: .env

networks:
  zhangli:
    driver: bridge
