version: '2'

services:
  redis:
    image: redis:alpine
    container_name: redis-service
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    restart: always
  apollo-db:
    image: mysql:5.7
    container_name: mysql-service
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 123456
    depends_on:
      - service-dbdata
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    volumes_from:
      - service-dbdata
    restart: always
  service-dbdata:
    image: alpine:latest
    container_name: apollo-dbdata
    volumes:
      - /var/lib/mysql
