version: '3'
services:
  eureka-service:
    networks:
      - dev
    container_name: eureka-service
    image: stanic-docker.pkg.coding.net/qing/qing/qing-eureka-service:1.0.0.RELEASE
    ports:
      - "8761:8761"
    environment:
      TZ: Asia/Shanghai
      ENV: prod
  config-server:
    restart: always
    networks:
      - dev
    image: stanic-docker.pkg.coding.net/qing/qing/qing-config-git:1.0.0.RELEASE
    container_name: config-service
    ports:
      - "8888:8888"
    environment:
      TZ: Asia/Shanghai
      ENV: prod
networks:
  dev:
    driver: bridge
