version: '2'
services:
  eureka-service:
    networks:
      - dev
    container_name: vo-service
    image: stanic-docker.pkg.coding.net/qing/qing/qing-service-vo:1.0.0.RELEASE
    ports:
      - "80:8080"
    environment:
      TZ: Asia/Shanghai
      ENV: prod

networks:
  dev:
    driver: bridge
