version: '2'
services:
  eureka-service:
    networks:
      - dev
    container_name: eureka-service
    image: stanic-docker.pkg.coding.net/zhangli/zhangli/zhangli-service-provider:1.0.0.RELEASE
    ports:
      - "5555:8080"
    environment:
      TZ: Asia/Shanghai
      ENV: prod

networks:
  dev:
    driver: bridge
