server:
  port: 9001
spring:
  application:
    name: zhangli-feign-client
ribbon:
  eureka:
    enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli
    fetch-registry: true
    register-with-eureka: true
feign:
  compression:
    response:
      enabled: true
      useGzipDecoder: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  endpoint:
    health:
      show-details: always
debug: true
test: default
