server:
  port: 9001
spring:
  application:
    name: qing-feign-client
ribbon:
  eureka:
    enabled: true
feign:
  compression:
    response:
      enabled: true
      useGzipDecoder: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  endpoint:
    health:
      show-details: always
debug: true
test: default
