eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/spring-cloud-demo/config-server
        git:
          uri: https://gitee.com/stanChen/zhangli-config.git
          username: stanChen
          password: 4745701816long