server:
  port: 80
spring:
  application:
    name: qing-eureka-service
  profiles:
    active: prod
eureka:
  server:
    enable-self-preservation: true
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}
    prefer-ip-address: true

  dashboard:
    path: /dashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
