spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/qing?serverTimezone=GMT%2B8&
    hikari:
      username: root
      password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mail:
    host: smtp.qq.com
    username: your_mail_count
    password: your_mail_token
  cloud:
    config:
      enabled: false
    consul:
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
qing:
  openAopLog: true
  api:
    doc-disabled: false
  index-size: 26
  authing:
    appId: 6432d5c9e0502f0bb45319bf
    appSecret: a599ddfc87b4478596b31a17e46d2360
    appHost: https://stanic.authing.cn/6432d5c9e0502f0bb45319bf
    redirectUrl: http://localhost:8080/api/auth/authingLogin
  mp:
    # 测试账号
    appId: wx9e955703886af7c9
    secret: 9d8cbf48467d38006f50f13d499f5abc
    token: 123123
    aes-key: ZcipcxwIwYh0WFFdBPZXlrxzNVmTWPq4OuVh4RzHGh6
management:
  endpoint:
    consul:
      enabled: false
