version: '1.0'
name: devops
displayName: 自动化打包部署-Gitee
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - main
  pr:
    branches:
      prefix:
        - main
stages:
  - name: maven_build
    displayName: maven build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven Build
        jdkVersion: '17'
        mavenVersion: 3.6.3
        commands:
          - '# 功能：打包'
          - mvn clean package -pl qing-bootstrap/qing-bootstrap-service -am -f pom.xml
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - qing-bootstrap/qing-bootstrap-service/target/qing-bootstrap-service.jar
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'
      - step: build@docker
        name: docker_build
        displayName: Docker Build
        type: cert
        certificate: 3d32d0e0-00aa-013c-8d3b-62e879a5badf
        tag: qing-bootstrap-service:0.0.2.${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: qing-bootstrap/qing-bootstrap-service/Dockerfile
        context: qing-bootstrap/qing-bootstrap-service/target
        artifacts:
          - ${BUILD_ARTIFACT}
        isCache: true
        parameter: {}
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_maven
strategy:
  blocking: true
