version: '1.0'
name: devops
displayName: 自动化打包部署
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - main
  pr:
    branches:
      prefix:
        - main
stages:
  - name: pipeline-build-codegen-plugin
    displayName: codegen-plugin-build-tet
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '17'
        mavenVersion: 3.6.3
        commands:
          - '# 功能：打包'
          - cd ~/workspace/${GITEE_REPO}/
          - mvn clean install -pl !qing-ui -f pom.xml
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./qing-bootstrap/qing-bootstrap-service/target/qing-bootstrap-service.jar
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: stanic-docker.pkg.coding.net/qing/qing
        username: qing-1688924172946
        password: cb618ff5047b1b563b93472431ce9a4104ddc7b8
        tag: qing-bootstrap-service:0.0.2.${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./qing-bootstrap/qing-bootstrap-service/Dockerfile
        context: ./qing-bootstrap/qing-bootstrap-service
        artifacts: []
        isCache: true
        parameter: {}
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_maven
strategy:
  blocking: true
