version: '1.0'
name: pipeline-build-codegen-plugin
displayName: codegen-plugin-build
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
stages:
  - name: stage-baa998e4
    displayName: 拉取代码
    strategy: naturally
    trigger: auto
    executor:
      - stanChen
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '17'
        mavenVersion: 3.6.3
        commands:
          - pwd
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'
strategy:
  cloneDepth: 1
