eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-virtual-host-name: config.chenyunlong.cn
    virtual-host-name: config.host.chenyunlong.cn
  client:
    service-url:
      defaultZone: ${QING_EUREKA_URL}
