server:
  port: 10086
spring:
  application:
    name: qing-admin-server
  profiles:
    active: prod
  security:
    # 配置登录用户名和密码
    user:
      name: ${QING_ADMIN_USERNAME}
      password: ${QING_ADMIN_PASSWORD}
  boot:
    admin:
      discovery:
        ignored-services:
          - ${spring.application.name}
          - password
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.version@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
