eureka:
  instance:
    prefer-ip-address: false
    ip-address: ${QING_ADMIN_IP:127.0.0.1}
    hostname: ${QING_ADMIN_HOST:localhost}
    non-secure-port: ${QING_ADMIN_PORT}
    non-secure-port-enabled: true
    secure-virtual-host-name: ${QING_ADMIN_HOST}
    virtual-host-name: ${QING_ADMIN_HOST}
  client:
    service-url:
      defaultZone: ${QING_REGISTRY_EUREKA_URL}
