spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/zhangli?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 123456
  rabbitmq:
    username: guest
    password: guest
    host: localhost
  thymeleaf:
    cache: false
    prefix: file:${user.dir}/zhangli-service-provider/src/main/resources/templates/
  redis:
    host: 127.0.0.1
    port: 6379
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mp:
  wx:
    appId: wx09bf7e704a150a9c
    secret: 9fdb9fa846356d32247a9aa68d758791
zhangli:
  file:
    baseUploadDir: upload/
    image-server-url: http://localhost:8080
  # 是否异步记录用户操作日志
  openAopLog: true
  swagger:
    doc-disabled: false
  index-size: 26
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl