spring:
  datasource:
    url: jdbc:mysql://cdb-4fyv2fr8.cd.tencentcdb.com:10085/zhangli?serverTimezone=UTC
    hikari:
      username: root
      password: MysqlPwdROOT1996
  mail:
    host: smtp.qq.com
    username: 1576302867@qq.com
    password: xoqywcevpshnbabf
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.163.95:8848
        enabled: false
      config:
        server-addr: 121.36.163.95:8848
        enabled: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%5p] --- [%-24t] [%-50C{50}][%-6L]: %m%n"
  level:
    root: info
    person.pluto: info
    chenyunlong.zhangli.mapper: info
    chenyunlong.zhangli: info
mp:
  wx:
    appId: wx09bf7e704a150a9c
    secret: 9fdb9fa846356d32247a9aa68d758791
zhangli:
  file:
    baseUploadDir: upload/
    image-server-url: https://bangumi.chenyunlong.cn
  # 是否异步记录用户操作日志
  openAopLog: true
  swagger:
    doc-disabled: true
