server:
  port: 8080
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
    hostname: provider1
    prefer-ip-address: true
    ip-address: 121.36.163.95
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli
spring:
  application:
    name: zhangli-service-provider
  messages:
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-4fyv2fr8.cd.tencentcdb.com:10085/zhangli?serverTimezone=UTC
    hikari:
      username: root
      password: MysqlPwdROOT1996
      connection-timeout: 6000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 5
      minimum-idle: 10
      read-only: false
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 10MB
  mail:
    host: smtp.qq.com
    username: 1576302867@qq.com
    password: xoqywcevpshnbabf
ribbon:
  eureka:
    enabled: true

logging:
  config: ${LOG_CONFIG_PATH:}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%5p] --- [%-24t] [%-50C{50}][%-6L]: %m%n"
  level:
    root: info
    person.pluto: ${LOG_LEVEL:trace}
    chenyunlong: info


zhangli:
  file:
    baseUploadDir: upload/
    image-server-url: http://www.stanic.xyz/pic/
  openAopLog: true # 是否异步记录用户操作日志
  swagger:
    author: Stan
    basePackage: chenyunlong.zhangli
    description: Zhangli's Rear Gargen  API Document.
    email: 1576302867@qq.com
    license: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
    title: Stan's Application for Zhangli
    url: http://www.chenyunlong.cn
    version: @project.version@
  security:
    authticationPrefix: authentication_


#微信订阅号
mp:
  wx:
    appId: wx09bf7e704a150a9c
    secret: 9fdb9fa846356d32247a9aa68d758791
redisson:
  address: redis://localhost:6379
  password:
  master-name: mymaster
common:
  constants:
    ## 服务端的签名key，散列算法，约等于对称密钥，客户端使用签名方式获取接口状态
    SERVER_SIGN_KEY: ${SERVER_SIGN_KEY:serverSignKey}
    SIGN_MAX_DIFF_MILLIS: 10000
debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis:
  mapper-locations: classpath:mapper/*.xml