server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}
    hostname: bangumi.chenyunlong.cn
    prefer-ip-address: true
    ip-address: 121.36.163.95
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli
spring:
  profiles:
    active: ${ENV:dev}
  application:
    name: zhangli-service-provider
  messages:
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 6000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 5
      minimum-idle: 10
      read-only: false
      connection-test-query: select 1
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 10MB
  mail:
    host: smtp.qq.com
    username: 1576302867@qq.com
    password: xoqywcevpshnbabf
ribbon:
  eureka:
    enabled: true
zhangli:
  file:
    baseUploadDir: upload/
    image-server-url: http://www.stanic.xyz/pic/
  # 是否异步记录用户操作日志
  openAopLog: true
  swagger:
    author: Stan
    basePackage: chenyunlong.zhangli
    description: Zhangli's Rear Gargen  API Document.
    email: 1576302867@qq.com
    license: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
    title: Stan's Application from Agefans
    url: http://bangumi.chenyunlong.cn
    version: V1.0.0
    doc-disabled: false
  security:
    authenticationPrefix: authentication_
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis:
  mapper-locations: classpath:mapper/*.xml