server:
  port: 8080
spring:
  profiles:
    active: prod
  application:
    name: zhangli-service-provider
  messages:
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    hikari:
      connection-timeout: 6000
      validation-timeout: 1000
      idle-timeout: 60000
      login-timeout: 500
      max-lifetime: 60000
      maximum-pool-size: 2
      minimum-idle: 1
      read-only: false
      connection-test-query: select 1
      initialization-fail-timeout: 1000
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 10MB
  mail:
    host: smtp.qq.com
    username: 1576302867@qq.com
    password: uqvyyxhvhdpnbabg
  freemarker:
    template-loader-path: classpath:/templates/mail/
    suffix: .ftl
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    type: simple
  quartz:
    scheduler-name: testName
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    cache-enabled: off
  global-config:
    banner: false
  type-aliases-package: cn.chenyunlong.zhangli.**.domain,cn.chenyunlong.zhangli.**.entities
  mapper-locations: classpath*:mapper/**/*Mapper.xml
zhangli:
  file:
    baseUploadDir: upload/
    image-server-url: https://www.stanic.xyz/pic/
  # 是否异步记录用户操作日志
  openAopLog: true
  swagger:
    author: Stan
    basePackage: cn.chenyunlong.zhangli
    description: Zhangli's Rear Gargen  API Documentation.
    email: 1576302867@qq.com
    license: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
    title: Application from Agefans
    url: https://bangumi.chenyunlong.cn
    version: V1.0.0
    doc-disabled: false
  security:
    authenticationPrefix: authentication_
  index-size: 26
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always
mp:
  wx:
    app-id: wx09bf7e704a150a9c
    secret: 9fdb9fa846356d32247a9aa68d758791


