debug: true
server:
  port: 8080
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/zhangli?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 123456
  mail:
    host: smtp.qq.com
    username: 1576302867@qq.com
    password: uqvyyxhvhdpnbabg
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
  rabbitmq:
    username: guest
    password: guest
    host: localhost
  thymeleaf:
    cache: false
    prefix: file:${user.dir}/zhangli-service-provider/src/main/resources/templates/
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%5p] --- [%-24t] [%-50C{50}][%-6L]: %m%n"
  level:
    root: info
    person.pluto: info
    chenyunlong.zhangli.mapper: debug
    chenyunlong.zhangli: debug
mp:
  wx:
    appId: wx09bf7e704a150a9c
    secret: 9fdb9fa846356d32247a9aa68d758791
zhangli:
  file:
    baseUploadDir: upload/
    image-server-url: http://localhost:8080
  # 是否异步记录用户操作日志
  openAopLog: true
  swagger:
    doc-disabled: false
