server:
  port: 9527
spring:
  application:
    name: zhangli-zuul-client
eureka:
  instance:
    instance-id: ${spring.application.name}
ribbon:
  eureka:
    enabled: true
zuul:
  ignored-services: '*'
  routes:
    zhangli-feign-client: /userservice/**
    zhangli-service-provider: /anime/**

management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  endpoint:
    health:
      show-details: always
