spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  security:
    user:
      name: user
      password: 123456
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
