server:
  port: 10086
spring:
  profiles:
    active: dev
  application:
    name: qing-bootstrap-monitor
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
  boot:
    admin:
      discovery:
        ignored-services:
          - consul
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
info:
  version: '@project.version@'
  name: '@project.artifactId@'
  group: '@project.groupId@'
  description: '@project.description@'
