server:
  port: 10086
spring:
  application:
    name: qing-bootstrap-monitor
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
info:
  version: '@project.version@'
  name: '@project.artifactId@'
  group: '@project.groupId@'
  description: '@project.description@'
