server:
  port: 10086
spring:
  application:
    name: qing-admin-server
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.16:8761/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
