spring:
  cloud:
    consul:
      discovery:
        enabled: true
        heartbeat:
          enabled: false
        register-health-check: false
      host: ${QING_CONSUL_HOST}
      port: ${QING_CONSUL_PORT}
