server:
  port: 8888
spring:
  application:
    name: qing-config-git
  cloud:
    config:
      server:
        default-label: master
        git:
          search-paths: config-repo
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: default
      status: UP
      profile: prod
