eureka:
  instance:
    ip-address: 121.36.163.95
    hostname: config.chenyunlong.cn
    prefer-ip-address: true
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli
    service-url:
      defaultZone: http://121.36.163.95:8761/eureka/