server:
  port: 8888
spring:
  application:
    name: zhangli-config-git
  profiles:
    active: prod

eureka:
  client:
    use-dns-for-fetching-service-urls: true
    eureka-server-d-n-s-name: chenyunlong.cn
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 8761
    prefer-same-zone-eureka: true
    region: zhangli
