apiVersion: apps/v1
kind: Deployment
metadata:
  name: qing-config-git
  namespace: qing
  labels:
    app: halo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qing-config-git
  template:
    metadata:
      labels:
        app: qing-config-git
    spec:
      containers:
        - name: halo
          image: stanic-docker.pkg.coding.net/qing/qing/qing-config-git:0.0.2.64
          ports:
            - containerPort: 8888
              hostPort: 8888
          livenessProbe:
            httpGet:
              port: 8888
              path: /
