eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    hostname: localhost
    ip-address: 127.0.0.1
    prefer-ip-address: true