server:
  port: 8761
spring:
  application:
    name: zhangli-eureka-service
  cloud:
    inetutils:
      ignored-interfaces[0]: eth0
eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
    hostname: eureka.chenyunlong.cn
    prefer-ip-address: true
    ip-address: 121.36.163.95