server:
  port: 8761
eureka:
  server:
    enable-self-preservation: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'