server:
  port: 8761
eureka:
  server:
    enable-self-preservation: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    hostname: eureka.chenyunlong.cn
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
#    ip-address: 127.0.0.1
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'