server:
  port: 8761
eureka:
  server:
    enable-self-preservation: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://121.36.163.95:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}:@project.version@
    ip-address: 121.36.163.95
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'