# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches:
      - '**'
    paths:
      - ".github/workflows/build.yml"
      - "pom.xml"
      - "qing-bom/**"
      - "qing-commons"
      - "qing-domain/**"
      - "qing-starters/**"
      - "qing-infrastructure/**"
      - "qing-infrastructure-anime/**"
      - "qing-application/qing-application-manager/**"
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt-hotspot'
          cache: maven
      - name: Build Web Service
        run: mvn --no-transfer-progress clean package -pl qing-application/qing-application-manager -am -f pom.xml
