# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt-hotspot'
          cache: maven
      - name: Build Codegen Plugin
        run: mvn clean install -pl qing-codegen-plugin/qing-codegen-apt -am -f pom.xml
      - name: Build Security Starter
        run: mvn clean install -pl qing-starters/qing-security-spring-boot-starter -f pom.xml
      - name: Build Infrastructure
        run: mvn clean install -pl qing-infrastructure -f pom.xml
      - name: Build Domain Service
        run: mvn clean install -pl qing-domain -am -f pom.xml
      - name: Build Web Service
        run: mvn clean install -pl qing-application/qing-application-manager -f pom.xml
