# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: coding
    env:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt-hotspot'
          cache: maven
      - name: Build with Maven
        run: cd qing-bom && mvn install
      - name: Build qing-commons
        run: cd qing-common-starters && mvn clean install
      - name: Build qing-commons
        run: cd qing-commons && mvn clean install
      - name: Build Docker Image and Push to Docker Hub
        run: cd qing-service-anime && mvn clean package -B
