# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  USERNAME: zhangli-1615218686182
  PASSWORD: d120bcc800ffcb7f527ad9429f81cc50ac3e5542
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt-hotspot'
          cache: maven
      - name: Print environment variables
        run: echo "打印 ${{ env.USERNAME }}${{ env.PASSWORD }}"
      - name: Build with Maven
        run: cd zhangli-bom && mvn install
      - name: Build Docker Image and Push to Docker Hub
        run: cd zhangli-service-provider && mvn clean package dockerfile:build dockerfile:tag dockerfile:push -Dregistry_username=${USERNAME} -Dregistry_password=${PASSWORD} --file pom.xml -B